/*
 * File: RecuperaArchCaller.java  2008/09/02 15:05:55
 * User: Daniel Hernandez N. (Tesoreria General de la Republica)
 *
 * This file was generated by "OBCOM SQL Wizard" version 5.1.236.
 * Copyright (c) OBCOM INGENIERIA S.A. (Chile) All rights reserved.
 * OBCOM PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 * DO NOT EDIT THIS FILE <<Signature:vm9UTs8GZoSkSShgLcSki3>>.
 */

package cl.tesoreria.monex.pkgconsultasmonex;

import cl.tesoreria.monex.vo.PContabVO;
import java.math.BigDecimal;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Types;
import java.util.ArrayList;
import javax.sql.RowSet;

/**
 * Implements a caller of procedure "PKG_CONSULTAS_MON_EX.PERIODOS_CONTABLES".
 */
public class ActPContablesCaller extends ProcedureCaller
{
    /**
     * Executes procedure "PKG_CONSULTAS_MON_EX.ACT_P_CONTABLES".
     *
     * CURSOR_RS         REF CURSOR         Output
     */
    public static void execute(Connection conn, String periodoIn)
        throws java.sql.SQLException
    {
        CallableStatement call = conn.prepareCall("{call SII.PKG_CONSULTAS_MON_EX.ACT_P_CONTABLES(?)}");
        try
        {
            call.setString(1,periodoIn);
            call.execute();
        }
        finally
        {
            call.close();
        }
        
        return;
    }
}
