/*
 * File: ExpFormCaller.java  2008/09/02 15:05:55
 * User: Daniel Hernandez N. (Tesoreria General de la Republica)
 *
 * This file was generated by "OBCOM SQL Wizard" version 5.1.236.
 * Copyright (c) OBCOM INGENIERIA S.A. (Chile) All rights reserved.
 * OBCOM PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 * DO NOT EDIT THIS FILE <<Signature:JmyWGgKfpSLFOCepk+CbKy>>.
 */

package cl.tesoreria.monex.pkgconsultasmonex;

import java.math.BigDecimal;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.sql.RowSet;

/**
 * Implements a caller of procedure "SII.PKG_CONSULTAS_MON_EX.EXP_FORM".
 */
public class ExpFormCaller extends ProcedureCaller
{
    /**
     * Executes procedure "SII.PKG_CONSULTAS_MON_EX.EXP_FORM".
     *
     * RUT_IN             NUMBER             Input
     * DV_IN              CHAR(2000)         Input
     * FORM_IN            NUMBER             Input
     * FOLIO_IN           NUMBER             Input
     * DESDE_IN           VARCHAR2(4000)     Input
     * HASTA_IN           VARCHAR2(4000)     Input
     * VENC_IN            VARCHAR2(4000)     Input
     * CURSOR             REF CURSOR         Output
     */
    public static ExpFormResult execute(Connection conn, BigDecimal rutIn, String dvIn, BigDecimal formIn, BigDecimal folioIn, String desdeIn, String hastaIn, String vencIn)
        throws java.sql.SQLException
    {
        ExpFormResult result = new ExpFormResult();
        ArrayList resultSets = new ArrayList();
        if (conn.getMetaData().getURL().startsWith("jdbc:oracle:"))
        {
            CallableStatement call = conn.prepareCall("{call SII.PKG_CONSULTAS_MON_EX.EXP_FORM(?,?,?,?,?,?,?,?)}");
            try
            {
                call.setBigDecimal(1, rutIn);
                call.setString(2, dvIn);
                call.setBigDecimal(3, formIn);
                call.setBigDecimal(4, folioIn);
                call.setString(5, desdeIn);
                call.setString(6, hastaIn);
                call.setString(7, vencIn);
                call.registerOutParameter(8, ORACLE_CURSOR);
                call.execute();
                resultSets.add(toRowSet((ResultSet) call.getObject(8)));
            }
            finally
            {
                call.close();
            }
        }
        else
        {
            CallableStatement call = conn.prepareCall("{call SII.PKG_CONSULTAS_MON_EX.EXP_FORM(?,?,?,?,?,?,?)}");
            try
            {
                call.setBigDecimal(1, rutIn);
                call.setString(2, dvIn);
                call.setBigDecimal(3, formIn);
                call.setBigDecimal(4, folioIn);
                call.setString(5, desdeIn);
                call.setString(6, hastaIn);
                call.setString(7, vencIn);
                int updateCount = 0;
                boolean haveRset = call.execute();
                while (haveRset || updateCount != -1)
                {
                    if (!haveRset)
                        updateCount = call.getUpdateCount();
                    else
                        resultSets.add(toRowSet(call.getResultSet()));
                    haveRset = call.getMoreResults();
                }
            }
            finally
            {
                call.close();
            }
        }
        if (resultSets.size() > 0)
        {
            RowSet[] rowSets = new RowSet[resultSets.size()];
            result.setRowSets((RowSet[]) resultSets.toArray(rowSets));
        }
        return result;
    }
}
