/*
 * File: GeneraHuinchaCaller.java  2008/09/02 15:05:55
 * User: Daniel Hernandez N. (Tesoreria General de la Republica)
 *
 * This file was generated by "OBCOM SQL Wizard" version 5.1.236.
 * Copyright (c) OBCOM INGENIERIA S.A. (Chile) All rights reserved.
 * OBCOM PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 * DO NOT EDIT THIS FILE <<Signature:KMKN0GTbFav+vbH+t97iEN>>.
 */

package cl.tesoreria.monex.pkgconsultasmonex;

import java.math.BigDecimal;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Types;
import java.util.ArrayList;
import javax.sql.RowSet;

/**
 * Implements a caller of procedure "SII.PKG_CONSULTAS_MON_EX.GENERA_HUINCHA".
 */
public class GeneraHuinchaCaller extends ProcedureCaller
{
    /**
     * Executes procedure "SII.PKG_CONSULTAS_MON_EX.GENERA_HUINCHA".
     *
     * FILES_HUINCHA_RS   REF CURSOR         Output
     * MENSAJE_RETORNO    VARCHAR2(4000)     Output
     * COD9927_AUX        NUMBER             Input
     */
    public static GeneraHuinchaResult execute(Connection conn, BigDecimal cod9927Aux)
        throws java.sql.SQLException
    {
        GeneraHuinchaResult result = new GeneraHuinchaResult();
        ArrayList resultSets = new ArrayList();
        if (conn.getMetaData().getURL().startsWith("jdbc:oracle:"))
        {
            CallableStatement call = conn.prepareCall("{call SII.PKG_CONSULTAS_MON_EX.GENERA_HUINCHA(?,?,?)}");
            try
            {
                call.registerOutParameter(1, ORACLE_CURSOR);
                call.registerOutParameter(2, Types.VARCHAR);
                call.setBigDecimal(3, cod9927Aux);
                call.execute();
                resultSets.add(toRowSet((ResultSet) call.getObject(1)));
                result.setMensajeRetorno(call.getString(2));
            }
            finally
            {
                call.close();
            }
        }
        else
        {
            CallableStatement call = conn.prepareCall("{call SII.PKG_CONSULTAS_MON_EX.GENERA_HUINCHA(?,?)}");
            try
            {
                call.registerOutParameter(1, Types.VARCHAR);
                call.setBigDecimal(2, cod9927Aux);
                int updateCount = 0;
                boolean haveRset = call.execute();
                while (haveRset || updateCount != -1)
                {
                    if (!haveRset)
                        updateCount = call.getUpdateCount();
                    else
                        resultSets.add(toRowSet(call.getResultSet()));
                    haveRset = call.getMoreResults();
                }
                result.setMensajeRetorno(call.getString(1));
            }
            finally
            {
                call.close();
            }
        }
        if (resultSets.size() > 0)
        {
            RowSet[] rowSets = new RowSet[resultSets.size()];
            result.setRowSets((RowSet[]) resultSets.toArray(rowSets));
        }
        return result;
    }
}
