/*
 * File: RecuperaArchCaller.java  2008/09/02 15:05:55
 * User: Daniel Hernandez N. (Tesoreria General de la Republica)
 *
 * This file was generated by "OBCOM SQL Wizard" version 5.1.236.
 * Copyright (c) OBCOM INGENIERIA S.A. (Chile) All rights reserved.
 * OBCOM PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 * DO NOT EDIT THIS FILE <<Signature:vm9UTs8GZoSkSShgLcSki3>>.
 */

package cl.tesoreria.monex.pkgconsultasmonex;

import cl.tesoreria.monex.vo.PContabVO;
import java.math.BigDecimal;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Types;
import java.util.ArrayList;
import javax.sql.RowSet;

/**
 * Implements a caller of procedure "SII.PKG_CONSULTAS_MON_EX.PERIODOS_CONTABLES".
 */
public class PeriodosContablesCaller extends ProcedureCaller
{
    /**
     * Executes procedure "SII.PKG_CONSULTAS_MON_EX.PERIODOS_CONTABLES".
     *
     * CURSOR_RS         REF CURSOR         Output
     */
    public static PeriodosContablesResult execute(Connection conn, BigDecimal anno)
        throws java.sql.SQLException
    {
        //ArrayList result = new ArrayList();
        //ResultSet rs = null;
        PeriodosContablesResult result =  new PeriodosContablesResult();
        ArrayList resultSets = new ArrayList();
        
        if (conn.getMetaData().getURL().startsWith("jdbc:oracle:"))
        {
            CallableStatement call = conn.prepareCall("{call SII.PKG_CONSULTAS_MON_EX.PERIODOS_CONTABLES(?,?)}");
            try
            {
                call.setBigDecimal(1,anno);
                call.registerOutParameter(2, ORACLE_CURSOR);
                call.execute();
                resultSets.add(toRowSet((ResultSet) call.getObject(2)));
                /*rs = (ResultSet) call.getObject(2);
                while (rs.next()) {
                    PContabVO vo = new PContabVO();
                    vo.setPeriodo(rs.getString("PCONTAB"));
                    vo.setAbierto(rs.getString("ABIERTO"));
                    vo.setSeleccion(false);
                    result.add(vo);
                } // End While*/
                
            }
            finally
            {
                //rs.close();
                call.close();
            }
        } /*
        else
        {
            CallableStatement call = conn.prepareCall("{call SII.PKG_CONSULTAS_MON_EX.PERIODOS_CONTABLES(?)}");
            try
            {
                int updateCount = 0;
                boolean haveRset = call.execute();
                while (haveRset || updateCount != -1)
                {
                    if (!haveRset)
                        updateCount = call.getUpdateCount();
                    else
                        resultSets.add(toRowSet(call.getResultSet()));
                    haveRset = call.getMoreResults();
                }
            }
            finally
            {
                call.close();
            }
        } */
        if (resultSets.size() > 0)
        {
            RowSet[] rowSets = new RowSet[resultSets.size()];
            result.setRowSets((RowSet[]) resultSets.toArray(rowSets));
        }
        return result;
    }
}
