/*
 * File: PkgConsultasMonExException.java  2008/09/02 15:05:55
 * User: Daniel Hernandez N. (Tesoreria General de la Republica)
 *
 * This file was generated by "OBCOM SQL Wizard" version 5.1.236.
 * Copyright (c) OBCOM INGENIERIA S.A. (Chile) All rights reserved.
 * OBCOM PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 * DO NOT EDIT THIS FILE <<Signature:vSI1X-qjDQLPL7-czT-+Mb>>.
 */

package cl.tesoreria.monex.pkgconsultasmonex;

/**
 * Exception thrown when the execution of a procedure fails.
 */
public class PkgConsultasMonExException extends Exception
{
    private static final long serialVersionUID = 1L;

    /**
     * Create a new PkgConsultasMonExException.
     */
    public PkgConsultasMonExException()
    {
        super();
    }

    /**
     * Create a new PkgConsultasMonExException with supplied message.
     */
    public PkgConsultasMonExException(String message)
    {
        super(message);
    }

    /**
     * Create a new PkgConsultasMonExException with supplied cause.
     */
    public PkgConsultasMonExException(Throwable cause)
    {
        super(cause);
    }

    /**
     * Create a new PkgConsultasMonExException with supplied message and cause.
     */
    public PkgConsultasMonExException(String message, Throwable cause)
    {
        super(message, cause);
    }
}
