/*
 * File: RecuperaArchCaller.java  2008/09/02 15:05:55
 * User: Daniel Hernandez N. (Tesoreria General de la Republica)
 *
 * This file was generated by "OBCOM SQL Wizard" version 5.1.236.
 * Copyright (c) OBCOM INGENIERIA S.A. (Chile) All rights reserved.
 * OBCOM PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 * DO NOT EDIT THIS FILE <<Signature:vm9UTs8GZoSkSShgLcSki3>>.
 */

package cl.tesoreria.monex.pkgconsultasmonex;

import java.math.BigDecimal;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Types;
import java.util.ArrayList;
import javax.sql.RowSet;

/**
 * Implements a caller of procedure "SII.PKG_CONSULTAS_MON_EX.RECUPERA_ARCH".
 */
public class RecuperaArchCaller extends ProcedureCaller
{
    /**
     * Executes procedure "SII.PKG_CONSULTAS_MON_EX.RECUPERA_ARCH".
     *
     * FECHA_IN           NUMBER             Input
     * TIPOARCH_IN        VARCHAR2(4000)     Input
     * ID_IN              NUMBER             Input
     * ARCHCLOB           CLOB               Output
     * CURSOR_OUT         REF CURSOR         Output
     */
    public static RecuperaArchResult execute(Connection conn, BigDecimal fechaIn, String tipoarchIn, BigDecimal idIn)
        throws java.sql.SQLException
    {
        RecuperaArchResult result = new RecuperaArchResult();
        ArrayList resultSets = new ArrayList();
        if (conn.getMetaData().getURL().startsWith("jdbc:oracle:"))
        {
        	
        	System.out.println("AAAAAAAAAAAAAAAAA");
            CallableStatement call = conn.prepareCall("{call SII.PKG_CONSULTAS_MON_EX.RECUPERA_ARCH(?,?,?,?,?)}");
            try
            {
                call.setBigDecimal(1, fechaIn);
                call.setString(2, tipoarchIn);
                call.setBigDecimal(3, idIn);
                call.registerOutParameter(4, Types.CLOB);
                call.registerOutParameter(5, ORACLE_CURSOR);
                call.execute();
                result.setArchclob(toString(call.getClob(4)));
                resultSets.add(toRowSet((ResultSet) call.getObject(5)));
            }
            finally
            {
                call.close();
            }
        }
        else
        {
            CallableStatement call = conn.prepareCall("{call SII.PKG_CONSULTAS_MON_EX.RECUPERA_ARCH(?,?,?,?)}");
            try
            {
                call.setBigDecimal(1, fechaIn);
                call.setString(2, tipoarchIn);
                call.setBigDecimal(3, idIn);
                call.registerOutParameter(4, Types.CLOB);
                int updateCount = 0;
                boolean haveRset = call.execute();
                while (haveRset || updateCount != -1)
                {
                    if (!haveRset)
                        updateCount = call.getUpdateCount();
                    else
                        resultSets.add(toRowSet(call.getResultSet()));
                    haveRset = call.getMoreResults();
                }
                result.setArchclob(toString(call.getClob(4)));
            }
            finally
            {
                call.close();
            }
        }
        if (resultSets.size() > 0)
        {
            RowSet[] rowSets = new RowSet[resultSets.size()];
            result.setRowSets((RowSet[]) resultSets.toArray(rowSets));
        }
        return result;
    }
}
