<%--                                                                                  --%>
<%-- main.jsp                                                                         --%>
<%-- 2006-03-13:11:48:17                                                              --%>
<%--                                                                                  --%>
<%-- DO NOT EDIT THIS FILE                                                            --%>
<%--                                                                                  --%>
<%-- This file was generated by Novo 1.0                                              --%>
<%--                                                                                  --%>
<%@ page language="java" contentType="text/html;charset=UTF-8"%>
<%@taglib uri="http://beehive.apache.org/netui/tags-databinding-1.0" prefix="netui-data"%>
<%@taglib uri="http://beehive.apache.org/netui/tags-html-1.0" prefix="netui"%>
<%@taglib uri="http://beehive.apache.org/netui/tags-template-1.0" prefix="netui-template"%>
<netui:html>
  <head>
    <netui:base />
    <script language="JavaScript">
    function onLoad()
    {
        if (window != window.top)
            window.top.location = window.location;
    }
    </script>
    <title>Consultas Moneda Extranjera</title>
    <link href="<%=request.getContextPath()%>/resources/css/teso.css" type="text/css" rel="stylesheet"/>
  </head>
  <frameset cols="20%,80%" framespacing="1" frameborder="1" onLoad="onLoad()">
    <frame src="tree.jsp" scrolling="auto" name="frameLeft" frameborder="1" bordercolor="#003E7E" />
    <frame src="blank.jsp" scrolling="auto" name="frameRight" frameborder="0" />
  </frameset>
</netui:html>
